import type { CountryEntry, MessageItem, Profile } from "./types";

export const COUNTRIES: CountryEntry[] = [
  {
    country: "Greece",
    flag: "🇬🇷",
    status: "open",
    current: 2310,
    target: 2500,
    description: "Live — founders building in Greece.",
  },
  {
    country: "Germany",
    flag: "🇩🇪",
    status: "waitlist",
    current: 342,
    target: 1000,
    description: "342 founders waiting. Opens at 1,000.",
  },
  {
    country: "France",
    flag: "🇫🇷",
    status: "waitlist",
    current: 278,
    target: 1000,
    description: "278 founders waiting. Opens at 1,000.",
  },
  {
    country: "Spain",
    flag: "🇪🇸",
    status: "waitlist",
    current: 196,
    target: 1000,
    description: "196 founders waiting. Opens at 1,000.",
  },
  {
    country: "Italy",
    flag: "🇮🇹",
    status: "waitlist",
    current: 154,
    target: 1000,
    description: "154 founders waiting. Opens at 1,000.",
  },
  {
    country: "Netherlands",
    flag: "🇳🇱",
    status: "waitlist",
    current: 203,
    target: 1000,
    description: "203 founders waiting. Opens at 1,000.",
  },
];

export const SEED_MESSAGES: MessageItem[] = [
  {
    id: "1",
    author: {
      name: "Nikos Papadopoulos",
      username: "nikos",
      avatar: "NP",
      bio: "Founder building AI for SMEs",
      location: "Athens, Greece",
      website: "nikospapadopoulos.com",
      linkedin: "https://linkedin.com/in/nikos",
      country: "Greece",
      joinedAt: "Joined May 2025",
      profileViews: 1284,
      followers: 382,
    },
    content: "Καλησπέρα σε όλους! 👋 Is anyone here building something in AI?",
    timestamp: "9:12 AM",
    links: ["https://greekfounders.com"],
    reactions: { "👍": 6, "🔥": 2, "🎉": 1, "💡": 4 },
  },
  {
    id: "2",
    author: {
      name: "Maria Georgiou",
      username: "maria",
      avatar: "MG",
      bio: "AI product builder",
      location: "Heraklion, Greece",
      website: "mariageorgiou.io",
      country: "Greece",
      joinedAt: "Joined April 2025",
      profileViews: 892,
      followers: 210,
    },
    content: "Yes! I'm working on an AI tool for Greek hotels. Would love to connect with other founders here.",
    timestamp: "9:14 AM",
    reactions: { "👍": 11, "🔥": 4, "🎉": 2, "💡": 8 },
  },
  {
    id: "3",
    author: {
      name: "Giorgos Alexiou",
      username: "giorgos",
      avatar: "GA",
      bio: "E-commerce & logistics",
      location: "Thessaloniki, Greece",
      website: "giorgos.dev",
      twitter: "https://x.com/giorgos",
      country: "Greece",
      joinedAt: "Joined January 2025",
      profileViews: 643,
      followers: 145,
    },
    content: "Nice! I'm building an e-commerce logistics startup in Thessaloniki 🚀 Would love to grab a call with anyone working on the supply chain side.",
    timestamp: "9:18 AM",
    reactions: { "👍": 9, "🔥": 3, "🎉": 5, "💡": 2 },
  },
  {
    id: "4",
    author: {
      name: "Elena Kostopoulou",
      username: "elena",
      avatar: "EK",
      bio: "Product strategist",
      location: "Patras, Greece",
      website: "elenakost.com",
      country: "Greece",
      joinedAt: "Joined March 2025",
      profileViews: 501,
      followers: 98,
    },
    content: "Would love to hear more about the AI hotel workflow @maria — anyone open to a quick intro call this week?",
    timestamp: "9:20 AM",
    reactions: { "👍": 5, "🔥": 1, "🎉": 0, "💡": 6 },
  },
];

export const DEFAULT_PROFILE: Profile = {
  name: "Your Name",
  username: "yourname",
  avatar: "YN",
  bio: "",
  location: "",
  website: "",
  twitter: "",
  linkedin: "",
  github: "",
  country: "Greece",
  joinedAt: `Joined ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}`,
  profileViews: 0,
  followers: 0,
};
